theme = "catppuccin-mocha"
confirm-before-quit = false
copy-on-select = true

[window]
decorations = "transparent"
opacity = 0.9
blur = true

[navigation]
mode = "Plain"

[fonts.regular]
family = "JetBrainsMono Nerd Font Propo"
features = ["liga", "calt"]
